builds:
  - goos: [darwin, windows]
    goarch: [amd64, arm64]

archives:
  - format_overrides:
      - goos: windows
        format: zip

release:
  github:
    owner: gonzaloserrano
    name: mdserve
